ising_no_obj: gui.cpp helper.cpp ising.cpp imgui
	c++ $(CFLAGS) $(IMG_CFLAGS) gui.cpp helper.cpp ising.cpp $(GFX_LIBS) $(PWD)/libimgui.so 
#c++ $(CFLAGS) $(IMG_CFLAGS) gui.cpp helper.cpp ising.cpp $(GFX_LIBS) -L./ -limgui -Wl,-rpath NOT WORKING

#original compile method
old: gui.cpp helper.cpp ising.cpp imgui/backends/imgui_impl_sdl.cpp imgui/backends/imgui_impl_opengl3.cpp imgui/imgui*.cpp
	c++ `sdl2-config --cflags` -I imgui -I imgui/backends gui.cpp helper.cpp ising.cpp imgui/backends/imgui_impl_sdl.cpp imgui/backends/imgui_impl_opengl3.cpp imgui/imgui*.cpp `sdl2-config --libs` -lGL -ldl

